name: 'build-eips'

description: 'Run the build-eips tool'

inputs:
  args:
    description: 'Command-line arguments to pass to build-eips'
    required: true

outputs:
  stdout:
    description: 'Standard output from build-eips'
    value: ${{ steps.run-build-eips.outputs.stdout }}

runs:
  using: "composite"
  steps:
      - name: Rust Cache
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
        with:
          shared-key: build-eips

      - name: Install build-eips
        id: install-build-eips
        shell: bash
        run: |
          WHERE="$(mktemp -d)"
          (
            cd "$WHERE";
            wget https://github.com/eips-wg/preprocessor/releases/latest/download/build-eips-ubuntu.tar.xz;
            tar xvf build-eips-ubuntu.tar.xz;
          )
          echo "bin=$WHERE/build-eips" >> "$GITHUB_OUTPUT"

      - name: Install Zola
        shell: bash
        id: install-zola
        run: |
          set -euf -o pipefail
          ZOLA_VERSION="v0.22.1"
          ZOLA_DIGEST="0ca09aa40376aaa9ddfb512ff9ad963262ef95edb0d0f2d5ec6961b6f5cf22ef"
          WHERE="$(mktemp -d)"
          (
            cd "$WHERE";
            wget "https://github.com/getzola/zola/releases/download/${ZOLA_VERSION}/zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz";
            echo "${ZOLA_DIGEST}  zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | sha256sum -c
            tar xvf "zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz";
          )
          echo "path=$WHERE" >> "$GITHUB_OUTPUT"

      - name: Run build-eips
        id: run-build-eips
        shell: bash
        env:
          BUILD_EIPS_ARGS: ${{ inputs.args }}
          BUILD_EIPS: ${{ steps.install-build-eips.outputs.bin }}
          ZOLA_PATH: ${{ steps.install-zola.outputs.path }}
        run: |
          set -euf -o pipefail
          write_eof() {
            echo -e "\nEOF" >> "$GITHUB_OUTPUT"
          }
          echo "stdout<<EOF" >> "$GITHUB_OUTPUT"
          trap write_eof EXIT
          export PATH="${ZOLA_PATH}:${PATH}"
          "$BUILD_EIPS" --staging $BUILD_EIPS_ARGS | awk '{ print; if ($0 == "EOF") exit 1 }' | tee -a "$GITHUB_OUTPUT"
